/* Auto-generated by cbindgen. Do not edit. */

#ifndef LIBAGENT_H
#define LIBAGENT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct MetricsData {
  uint64_t agent_spawns;
  uint64_t trace_agent_spawns;
  uint64_t agent_failures;
  uint64_t trace_agent_failures;
  double uptime_seconds;
  uint64_t proxy_get_requests;
  uint64_t proxy_post_requests;
  uint64_t proxy_put_requests;
  uint64_t proxy_delete_requests;
  uint64_t proxy_patch_requests;
  uint64_t proxy_head_requests;
  uint64_t proxy_options_requests;
  uint64_t proxy_other_requests;
  uint64_t proxy_2xx_responses;
  uint64_t proxy_3xx_responses;
  uint64_t proxy_4xx_responses;
  uint64_t proxy_5xx_responses;
  double response_time_ema_all;
  double response_time_ema_2xx;
  double response_time_ema_4xx;
  double response_time_ema_5xx;
  uint64_t response_time_sample_count;
  uint64_t dogstatsd_requests;
  uint64_t dogstatsd_successes;
  uint64_t dogstatsd_errors;
} MetricsData;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void Initialize(void);

void Stop(void);

struct MetricsData GetMetrics(void);

int32_t ProxyTraceAgent(const char *method,
                        const char *path,
                        const char *headers,
                        const uint8_t *body_ptr,
                        size_t body_len,
                        const void *on_response,
                        const void *on_error,
                        void *user_data);

int32_t SendDogStatsDMetric(const uint8_t *payload_ptr, size_t payload_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIBAGENT_H */
