/* Auto-generated by cbindgen. Do not edit. */

#ifndef LIBAGENT_H
#define LIBAGENT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void Initialize(void);

void Stop(void);

int32_t ProxyTraceAgent(const char *method,
                        const char *path,
                        const char *headers,
                        const uint8_t *body_ptr,
                        size_t body_len,
                        const void *on_response,
                        const void *on_error,
                        void *user_data);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIBAGENT_H */
